### ISSUE TITLE
Flatland libraries are unmaintained, currently preventing JDK11 support

### ISSUE THREAD

**Issue by lvh** [circleci/clj-yaml#22]
Example: https://github.com/amalloy/ordered/pull/37

This is currently reflected in not being able to use JDK11, but of course it's a matter of time before more issues pop up. It takes _forever_ to get patches filed, speaking from experience.

You may be able to switch to another fork in the graph: https://github.com/amalloy/ordered/network

**Comment by marcomorain** [comment]
Hi @lvh thanks for pointing this out.

I'll add an item to our internal JIRA to think about the best way forward here.

**Comment by danielcompton** [comment]
CLJ Commons has taken over maintenance of ordered, we're keen to try and get this fixed, happy for any people to help get the referenced PR merged.

**Comment by lvh** [comment]
Oh hey, fantastic! I would like to point out that my original comment links to a ticket, but GitHub helpfully changed the link to point to clj-commons -- now it looks like I'm showing a link to the clj-commons  as evidence that the library is bad and you shouldn't use it. I have every faith in clj-commons (and anything @danielcompton-adjacent) doing a great job here, and retract my suggestion to get rid of the dependency or use a different fork.
