### ISSUE TITLE
Publish new build to clojars.  

### ISSUE THREAD

**Issue by mikeThurmond** [circleci/clj-yaml#24]
It looks like you bumped the org.flatland/ordered version to 1.5.7 in our project clj, but your clojars page says you still depend on org.flatland/ordered 1.5.5.  Can you publish a new build on clojars so https://github.com/ngrunwald/ring-middleware-format can publish a new build?

thanks!

**Comment by marcomorain** [comment]
I'll get this done tomorrow 👍

**Comment by marcomorain** [comment]
0.6.0 has been published. 👌
